apiVersion: v1
kind: Service
metadata:
  name: vprodb
spec:
  selector:
    app: vprodb
  ports:
  - port: 3306
    targetPort: 3306
    #MySQL DB Listening Port
    #to the DB Deployment Pod
    protocol: TCP
  type: ClusterIP