apiVersion: v1
kind: Service
metadata:
  name: vprocache01
  #must be the same with application.properties file in the artifact
spec:
  selector:
    app: vpromc
  ports:
  - port: 11211
    targetPort: 11211
    #to the MC Deployment Pod
    protocol: TCP
  type: ClusterIP
