apiVersion: v1
kind: Service
metadata:
  name: vpromq01
  #must be the same with application.properties file in the artifact
spec:
  selector:
    app: vpromq01
  ports:
  - port: 15672
    targetPort: 15672
    #to the RMQ Deployment Pod
    protocol: TCP
  type: ClusterIP
