apiVersion: v1
kind: Service
metadata:
  name: vproapp-service
  #must be the same with application.properties file in the artifact
spec:
  selector:
    app: vproapp
  ports:
  - port: 80
    targetPort: 8080
    #to the MC Deployment Pod
    protocol: TCP
  type: LoadBalancer
